### ISSUE TITLE
IScalarProperty causes SegFault when extent > 1

### ISSUE THREAD

**Issue by rbland** [alembic/alembic#138]
I recently tracked down a crashing bug in an internal tool. The problem arises when trying to read the value of a scalar property with non-default extent. I've attached a zip file with a minimal program demonstrating the crash as well as a minimum Alembic file to pass to it. I'm primarily testing on fedora 21 with gcc 4.9.2. 

If I've untangled the code correctly the crash is caused by calling **ITypedScalarProperty.getValue** which reserves memory for exactly one output value of type **value_type**. This memory location of the output value is passed through to **ITypedScalarProperty.get** and ultimately to **ReadData()** (in AbcCoreOgawa/ReadUtil.cpp); however, this function will try to read **sizeof(value_type) * extent** of bytes into this address. This results in corrupt memory which usually causes a segfault.

My understanding is that scalar properties can have any extent of 1 to 255 so my sample file is valid as far as I can tell. Perhaps IDoubleProperty::matches should fail if extent is not 1? Or should getValue throw an exception of some kind?

[property_crash_example.zip](https://github.com/alembic/alembic/files/1216462/property_crash_example.zip)

**Comment by lamiller0** [comment]
Hmmmm, thanks for pointing this out.

This was done at the same time as the ITypedArrayProperty.  It previously DID match against the extent, but was loosened up so that things like IV3fArrayProperty could also be treated like an IFloatArrayProperty.

This is to help with uses that may not care about all of the specialized variants but still want to read the data as just a big array property.

This works great for arrays, but may not make as much sense in the case for scalars.

I'm currently leaning towards making matches stricter for scalar properties, although the throw on an obviously wrong sized getValue is also attractive.

**Comment by lamiller0** [comment]
Merged in: https://github.com/alembic/alembic/commit/23d4db46a12ecbb37fa81831f2a7b9e74769c439
