### ISSUE TITLE
PyAlembic not working

### ISSUE THREAD

**Issue by cedricp** [alembic/alembic#142]
I don't know if I'm alone in this case, but I wasn't able to import the _alembic_ module in Python on Linux. The error was : 
`ImportError: dynamic module does not define init function (initalembic)`
I finally solved the problem by adding this to the _CMakeLists.txt_ in the _python/PyAlembic_ directory : 
```
    IF (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=default")
    ENDIF()
```
The main _CMakeLists.txt_ set `-fvisibility="hidden"`

**Comment by lamiller0** [comment]
Hmmmm, I wonder if something is different in your version of boost where boost python isn't making the
init explicitly visible?

**Comment by cedricp** [comment]
I'm using boost 1.65.1 and pyilmbase compiles the python module just fine.

**Comment by LoganKelly** [comment]
Thought I would just add that I had this exact same error using Alembic 1.7.4 and Boost 1.65.1 and the fix that @cedricp suggested also worked for me. This was on Fedora 21. Here's the rest of the stuff I built with too if that's helpful:
CMake 3.10.0
ILMBase/PyILMBase 2.2.1

**Comment by waebbl** [comment]
I got the same issue on a gentoo linux box. On 64bit, the above patch did solve it.

Because I want to enable alembic support in blender, which is also supported for 32 bit on gentoo, I also tried this on a 32 bit chroot. It compiles fine, but when I try to import the module I still get this error. I'm using boost-1.65.0, cmake-3.9.6 and the openexr-2.3.0 suite (ilmbase, openexr, pyilmbase) on both the 64 and 32 bit platforms.
