### ISSUE TITLE
Python 3 module initialization fails

### ISSUE THREAD

**Issue by charlesfleche** [alembic/alembic#216]
I'm trying to build Alembic against Python 3.7.3 on CentOS 7.4, using the software recommendations of the VXF Platform 2020. Alembic 1.7.11 builds (not the python tests, I had to deactivate them). However I can't import the Alembic module: it fails with a `SystemError`.

``` bash
$ python3 -c 'import alembic'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemError: initialization of alembic raised unreported exception
```

Does Alembic support Python 3 ?

**Comment by lamiller0** [comment]
I haven't tried to build both PyIlmBase and Alembic with python 3.
I imagine it depends on how much the version of boost you are using supports it.

I'm planning on doing a big refactor to support pybind 11 and drop the PyIlmBase dependency sometime soonish. (to make it easier to support VFX Platform 2020)

**Comment by charlesfleche** [comment]
I'm using boost 1.70, for the VFX Platform 2020.

**Comment by jasonliu--** [comment]
Are you trying to build PyAlembic (i.e. `-DUSE_PYALEMBIC=ON`)?

With all this quarantine free time due to the pandemic, I've been working to package Alembic/PyAlembic for MacPorts, and I ran into problems compiling against Python 3 as well. Here's how I got around it.

According to `cmake --help-module FindBoost`:
> Note that Boost Python components require a Python version suffix (Boost 1.67 and later), e.g. "python36" or "python27" for the versions built against Python 3.6 and 2.7, respectively.

Basically what this means is that when running cmake, `find_package()` will fail to generate a valid `Boost_PYTHON_LIBRARY` variable... and without it, the PyAlembic code won't be able to compile. In order to get around this problem, I had to go into the source code and make the following changes:
* In the `${ALEMBIC_SRC_DIR}/cmake/AlembicBoost.cmake` file, I had to modify the line `FIND_PACKAGE(Boost ... program_options python)` to be `FIND_PACKAGE(Boost ... program_options python37` (assuming you're using Python 3.7.3).
* In the `${ALEMBIC_SRC_DIR}/python/PyAlembic` directory, you need to replace all instances of `Boost_PYTHON_LIBRARY` with `Boost_PYTHON37_LIBRARY`, in all files.

At least for me, making these changes allowed PyAlembic to compile successfully against Python 3.7.7 and Boost 1.71.0.

**Comment by gia257** [comment]
@jasonliu-- did you try the tests? I built with boost 1.72 and am failing testCollections, the timesampling from the "cool" collection construction is not passing through into the c++ constructor

**Comment by arubertoson** [comment]
I had the same error, for me it related to not having the imath module in the PYTHONPATH

```bash
$ python3 -c "import alembic"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemError: initialization of alembic raised unreported exception
$ export PYTHONPATH="${PYTHONPATH}:/path/to/imath/module"
$ python3 -c "import alembic"

**Comment by lamiller0** [comment]
This should be much better in Alembic 1.8

**Comment by endlessll** [comment]
> Hi, I am running into the same issue with 1.8.3 on Ubuntu and python 3.8.5

Hi, Have you fixed the problem, I use the same environment and get the same issue, thanks
