### ISSUE TITLE
abc stitcher causing transformed geometry to become animated

### ISSUE THREAD

**Issue by grahamt-dd** [alembic/alembic#267]
Greetings!

At DD we've been encountering issues with the stitcher on heavy transforming geometry (rbds) generated out of FX with Houdini.  When using the stitcher to combine chunks it seems that attributes which should be static are randomly becoming animated and drasitcally increasing file sizes.  When we run the same geometry out to a single file this is not an issue.

Consider the attached examples files generated out of Houdini.

I've combined xforming_1.abc + xforming_121.abc to created combined.abc.  Inspecting the result it appears that the P attribute of a PolyMesh is now showing up as animated and thus increasing file size due to having all the geometry embedded compared to xforming.abc which is the same geometry generated in one go: 2.2mb vs 1.8mb.  Not so bad here but in an example production situation we're looking at 135gb vs 3gb.

[abc_stitcher_xform_issue.tar.gz](https://github.com/alembic/alembic/files/4602254/abc_stitcher_xform_issue.tar.gz)

Thanks!

**Comment by lamiller0** [comment]
It looks like the points ARE subtly animating between the 2 files.

foo/bar_instance1/bar  from 1 to 120 the first point is 0, 0, -1
at 121 and beyond  the first point is VERY close to the same:  4.4408920985e-16, 0.0, -1.0

Just a hunch,

I suspect you are using some sort of filtering in Houdini so that if its close by some metric it will write out the same sample, but when using it starting at frame 121 it uses a different starting value from what you exported starting at frame 1.


abc_stitcher doesn't attempt to do any filtering, and just uses the data as is.
