### ISSUE TITLE
Building on Rocky

### ISSUE THREAD

**Issue by suekieza** [alembic/alembic#448]
Hey there, me again >_<

I'm running into an issue building on Rocky, same build as I was doing on windows before(which now works :D).

My build args:

 [
  '-DOPENEXR_INSTALL_PKG_CONFIG=ON',
  '-DOPENEXR_BUILD_TOOLS=ON',
  '-DOPENEXR_BUILD_LIBS=ON',
  '_DOPENEXR_BUILD_EXAMPLES=ON',
  '-DOPENEXR_BUILD_PYTHON=ON',
  '-DOPENEXR_INSTALL_PYTHON=ON',
  '-DNUMPY_EXECUTABLE="{}"'.format(numpy_path),
  '-DOPENEXR_INSTALL_LIBS=ON',
  '-DOPENEXR_INSTALL_TOOLS=ON',
  '-DOPENEXR_INSTALL_EXAMPLES=ON',
  '-DOPENEXR_FORCE_INTERNAL_IMATH=ON',
  '-DPYTHON=ON',
  '-DPYBIND11=ON',
  '-DBoost_NO_BOOST_CMAKE=On',
  '-DBoost_NO_SYSTEM_PATHS=True',
  '-DCMAKE_DEBUG_POSTFIX=""',
  '-DCMAKE_VERBOSE_MAKEFILE=ON',
  '-DBUILD_TESTING=OFF'
]

building against openEXR, this time I made sure numpy and openexr build correctly(I think).
alembic build log:
[log.txt](https://github.com/alembic/alembic/files/15008891/log.txt)
openexr build log:
[log.txt](https://github.com/alembic/alembic/files/15008893/log.txt)

Not sure what I,m doing wrong this time, everything seems ok.....

Thanks for all the help really appreciate it.
Sue

**Comment by suekieza** [comment]
g++ (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4)
incase this helps

**Comment by lamiller0** [comment]
I do see:

-- Installing: /mnt/glasgow/siteConfig/software/rez_pkgs/axis/alembic/1.8.6/linux/lib64/libPyImath_Python3_10-3_1.so
-- Installing: /mnt/glasgow/siteConfig/software/rez_pkgs/axis/alembic/1.8.6/linux/lib/python3.10/site-packages/imath.so

In your OpenEXR build so thats good.

What Imath is it actually finding?

You may have to give it a little hint if its finding your distribution install instead of the one you installed to:
/mnt/glasgow/siteConfig/software/rez_pkgs/axis/alembic/1.8.6/linux

You may want to set -DPYILMBASE_ROOT to do this.

**Comment by lamiller0** [comment]
Also whats in your ImathTargets-release.cmake ?

**Comment by lamiller0** [comment]
What version of Imath are you using?  If its 3.1.11 or 3.1.10 there *might* be a problem there, but I think 3.1.9 should be okay.

**Comment by lamiller0** [comment]
There is this issue open on Imath right now: https://github.com/AcademySoftwareFoundation/Imath/issues/395

There will hopefully be a solution for it soon, if you confirm your issue goes away with Imath 3.1.9 that would be very helpful. (thats what I noticed on my builds)

**Comment by lamiller0** [comment]
I was able to build it on Rocky but had to work around the issue listed above.
